### ISSUE TITLE
Additional data needed for added provider details

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ms-macwis-prototype#103]
Specifically: 

USDA food program, hours and days of operation, special needs

**Comment by ClaireReinken** [comment]
o Hours of Operation ex. 7am - 5pm - Use variation of hours starting at 5:00am and ending at 8:00pm. 
 o Days of Operation ex. Sun, Mon, Wed, Fri - I would list the majority of providers at M - F and some from Sun - Sat or just M - Sat, etc. 
 o Provides Services for Children with Special Behavioral Needs - Data should be Yes or No
 o Provides Services for Children with Special Medical Needs - Data should be Yes or No
 o USDA Food Programs - Data should be Yes or No

**Comment by Bhavanireddy8** [comment]
Created Json file with all the changes mentioned above
