### ISSUE TITLE
MAWIS - Provider Search - Zip Code search display result not specific to Zip entry

### ISSUE THREAD

**Issue by johnjilek** [FEISystems/ms-macwis-prototype#105]
When the user searches for 39507, they should only get results for Harrison County, Gulfport City
When I look at the Provider Details for providers in the results, the Zip Code display differently.  There results for various counties and cities.

**Comment by lutech** [comment]
Cannot reproduce. Searching 39507 only returns providers with that zip.

**Comment by ClaireReinken** [comment]
This issue has been resolved
