### ISSUE TITLE
MACWIS - Provider Search - Any search input should be expanded if populated from Home page search

### ISSUE THREAD

**Issue by johnjilek** [FEISystems/ms-macwis-prototype#106]
When user performs a search from the home page, the inputs are populated into the Provider Search on the Provider Search page (as designed).  However, the Provider Search section is collapsed.  I suggest expanding any section that received an population of inputs.
i.e. If Provider Name was used to search, the "Search By Provider" section should be expanded to show the Provider Name input.

**Comment by ClaireReinken** [comment]
This functionality is in place
