### ISSUE TITLE
MACWIS - Provider Search - Provider checkbox floats vertically centered on mobile devices

### ISSUE THREAD

**Issue by johnjilek** [FEISystems/ms-macwis-prototype#114]
Provider checkbox floats vertically centered on mobile devices

Within the web version on a laptop/pc, the checkbox remains next to the Provider Name in the output.  
When utilizing mobile versions (i.e. iphone), the checkbox floats to center itself vertically within the details.  In this case the checkbox displays next to City.  If you click View More, the checkbox floats down (adjusting to be center) and displays next to Hours of Operation.
This requires the user to scroll and find the check box for a given provider instead of understanding the correlation when next to the provider name.

**Comment by christianhfei** [comment]
This has been addressed in a previous check-in. Just needs to be pulled into the main branch.

**Comment by johnjilek** [comment]
validated on iphone and ipad.  Closing
