### ISSUE TITLE
MACWIS - Mobile (iphone) - Provider checkboxes overlap with Provider Name in 'portrait' orientation

### ISSUE THREAD

**Issue by johnjilek** [FEISystems/ms-macwis-prototype#132]
Provider checkboxes overlap with Provider Name in 'portrait' orientation

Note:  The checkboxes display just fine when the phone is turned 'landscape' orientation.  The checkboxes also display fine on the ipad in both orientations.

**Comment by christianhfei** [comment]
Fixed with commit 6a598f126c9c7788046ea23deff5dfbfd18ad420
