### ISSUE TITLE
MACWIS - Provider Search - Results do not Sort By Provider Name correct

### ISSUE THREAD

**Issue by johnjilek** [FEISystems/ms-macwis-prototype#135]
Results do not Sort By Provider Name correct

Search for Providers with Provider Type "Group Home"
Sort By Provider Name
Change ascending descending
The sorted list displayed "Learning 4 Life Child Care" then "Anna Tatum", "Anna", Anna, etc.
 Sort again, the list displays "4th and Elms Cornerstone Christian", then "A Childs Choice", "A Childs Place"., etc.  

Sorting is questionable in this case.

**Comment by fei-xiangzhang** [comment]
the first is descending order, the second is ascending order. i thing the order is right.

**Comment by johnjilek** [comment]
After second looks, the whole data set is A's and one L provider name.  You are correct. Closing
