### ISSUE TITLE
MACWIS - Provider Search by Zip Code not displaying expected results

### ISSUE THREAD

**Issue by johnjilek** [FEISystems/ms-macwis-prototype#137]
When you enter Zip Code "39213" (Jackson, MS), then select within "50 miles", it only shows results in Jackson, MS.  This is incorrect because there are several counties and providers within 50 miles of Jackson. It should not be restricted to Jackson, MS (or the Zip Code entered).

**Comment by TerryBoswell** [comment]
The logic was fixed. Address logic was being called after geo filtering and should not have been
