### ISSUE TITLE
MACWIS - Provider Search - Search menu collapses after scrolling down (iphone)

### ISSUE THREAD

**Issue by johnjilek** [FEISystems/ms-macwis-prototype#139]
Search menu collapses after scrolling down (iphone)

Perform search
Click "Show Menu"
---Search menu is expanded and displayed
Scroll down to see other search inputs
**Search menu collapses automatically

**Comment by christianhfei** [comment]
Resolved with commit c65856a0c949363ce84807fa1182f263cc3e14d1
