### ISSUE TITLE
UI - multiple type device support

### ISSUE THREAD

**Issue by jtanus** [FEISystems/ms-macwis-prototype#27]
Need to work to make sure site works on different devices.

**Comment by jtanus** [comment]
Try to open site on Android phone. It is blank.

**Comment by johnjilek** [comment]
Testing has been done on Windows 8, 10, iOS9.  Browsers:  IE11, Google Chrome, and Safari.  Devices:  iPhone6, iPadAir, Samsung Galaxy, Surface Pro.
