### ISSUE TITLE
Several suggestions to enhance the UI of the search results

### ISSUE THREAD

**Issue by HatemGhafir** [FEISystems/ms-macwis-prototype#3]
1. The provider name spans two lines in many cases, with the second line separated from the first name by several line spacing
2. The five-stars span two lines.  Either we make the stars a little smaller or we re-organize the text
3. Suggestion to organize the text:
   FIRST LINE:  Provider Name       Type: xxx     star rating      link to Provider Details
   SECOND LINE: City      county     zip code     phone number

**Comment by ClaireReinken** [comment]
These issues have been addressed.
