### ISSUE TITLE
Link to the quality star definition

### ISSUE THREAD

**Issue by llin-freeman** [FEISystems/ms-macwis-prototype#47]
Please insert link to the quality star definition (page 2 of the PDF attached) 
[quality-stars-brochure.pdf](https://github.com/FEISystems/ms-macwis-prototype/files/509046/quality-stars-brochure.pdf)

and  here: (http://earlyyearsnetwork.msucares.com/system/files/website/quality-stars-brochure.pdf).

**Comment by jtanus** [comment]
The link is to open PDF a new tab

**Comment by Bhavanireddy8** [comment]
Working and link opens in new tab.
