### ISSUE TITLE
MACWIS - Provider Search - By Age - Provider with Age Range 5-10 does not show for search 10-12

### ISSUE THREAD

**Issue by johnjilek** [FEISystems/ms-macwis-prototype#51]
Provider with Age Range 5-10 does not show for search 10-12

Example:  Austin Eco Bilingual

**Comment by fei-xiangzhang** [comment]
1. there is not 5-10 option, there is 5-9 option.
2. if you select 5-9, the search logic is : minAge<=5 and MaxAge>=9.

**Comment by johnjilek** [comment]
No, the "5-10" is the Age Range of Provider "Austin Eco Bilingual School".  I see this provider when I select the Age Range filter "5-9", which makes sense because 5-9 falls in that.
However, when I select search filter "10-12", that same provider does not show up.

**Comment by johnjilek** [comment]
Discussed boundaries of search.  Closing.
