### ISSUE TITLE
search results order

### ISSUE THREAD

**Issue by ClaireReinken** [FEISystems/ms-macwis-prototype#67]
Can we list the data in this order?

Provider search results table will display the following information:
o   Address (County, City, Zip Code)
o   Provider Name
o   Provider Type
o   Star Rating
o   Phone Number
o   Hours of Operation ex. 7am - 5pm
o   Days of Operation ex. Sun, Mon, Wed, Fri
o   Licensed/Unlicensed
5.  Search Results will sort by “Distance” as default.
o   Nearest at the top.
6.  Provider details will display the following information:
o   Address (County, City, Zip Code)
o   Provider Name
o   Provider Type
o   Total Provider Capacity
o   Star Rating
o   Phone Number
o   Hours of Operation ex. 7am - 5pm
o   Days of Operation ex. Sun, Mon, Wed, Fri
o   Age Range
o   Licensed/Unlicensed
o   Provides services for children with Special Behavioral Needs
o   Provides services for children with Special Medical Needs
o   USDA Food Programs
o   Accepts Subsidized Child Care

**Comment by lutech** [comment]
Data in search results has be re-ordered, however, it follows the following order. After playing with the order, this seems to be the most logical. 
- Provider Name
- Distance From
- Star Rating
- Address
- Phone Number
- Provider Type
- Child Ages Accepted

**Additional Info (Popup was removed)**
- Hours of Operation
- Days of Operation
- Capacity
- Licensed/Unlicensed
- Gender Accepted
- Provides services for children with Special Behavioral Needs
- Provides services for children with Special Medical Needs
- Accepts Subsidized Child Care
- USDA Food Programs

**Comment by johnjilek** [comment]
Validated and Closing.
Entered a new bug regarding the "Show More" button not changing to "Show Less"
