### ISSUE TITLE
Mile search, check functionality

### ISSUE THREAD

**Issue by llin-freeman** [FEISystems/ms-macwis-prototype#88]
Please check the miles function? I searched zip code 39213 and 0 miles; the results showed some zip codes within 0 miles that were different zip codes.

**Comment by fei-xiangzhang** [comment]
when distance = 0 or null, local search doesn't work. it will return all the result, 5068 records.

**Comment by llin-freeman** [comment]
Thanks! It was really strange--some results showed number of miles, and some did not.  May I show you at the 4pm meeting?

**Comment by ClaireReinken** [comment]
We no longer can search by zero miles. Closing.
