### ISSUE TITLE
Group zip and distance field

### ISSUE THREAD

**Issue by llin-freeman** [FEISystems/ms-macwis-prototype#99]
Group zip code and distance field together in one panel (Search by Distance). City and County fields move up to the Provider panel.

**Comment by fei-xiangzhang** [comment]
If zip code has value and Distance >0, then search by distance
If Zip code has value and (Distance !>0 or "") then search by zip code
If Zip code = "", do nothing.

**Comment by johnjilek** [comment]
validated.  Closing
